name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Get package version from Packages directory
        id: version
        run: |
          if [ -f "Packages/dev.nekoare.tex-col-adjuster/package.json" ]; then
            VERSION=$(jq -r '.version' Packages/dev.nekoare.tex-col-adjuster/package.json)
            echo "Found version in Packages: $VERSION"
          else
            VERSION="1.2"
            echo "Using fallback version: $VERSION"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        
      - name: Create package ZIP file
        run: |
          echo "Creating ZIP from Packages/dev.nekoare.tex-col-adjuster directory"
          cd Packages/dev.nekoare.tex-col-adjuster
          zip -r ../../dev.nekoare.tex-col-adjuster-v${{ steps.version.outputs.version }}.zip . \
            -x "*.Zone.Identifier"
          cd ../..
          echo "Created ZIP file: dev.nekoare.tex-col-adjuster-v${{ steps.version.outputs.version }}.zip"
          
      - name: Calculate ZIP hash and update index.json
        run: |
          ZIP_HASH=$(sha256sum dev.nekoare.tex-col-adjuster-v${{ steps.version.outputs.version }}.zip | cut -d' ' -f1)
          echo "Generated ZIP hash for v${{ steps.version.outputs.version }}: $ZIP_HASH"
          
          # Create new version entry JSON
          cat > new_version.json << EOF
          {
            "name": "dev.nekoare.tex-col-adjuster",
            "displayName": "Texture Color Adjuster",
            "version": "${{ steps.version.outputs.version }}",
            "description": "Unity Editor extension for advanced texture color adjustment with support for various color spaces and intelligent color manipulation algorithms.",
            "unity": "2022.3",
            "unityRelease": "0f1",
            "author": {
              "name": "nekoare",
              "url": "https://github.com/nekoare"
            },
            "changelogUrl": "https://github.com/nekoare/texture-color-adjuster/blob/main/CHANGELOG.md",
            "documentationUrl": "https://github.com/nekoare/texture-color-adjuster/blob/main/README.md",
            "licenseUrl": "https://github.com/nekoare/texture-color-adjuster/blob/main/LICENSE",
            "vpmDependencies": {
              "com.vrchat.avatars": ">=3.7.0"
            },
            "keywords": [
              "texture",
              "color",
              "adjustment",
              "unity",
              "editor",
              "image processing",
              "color matching",
              "lab color space"
            ],
            "url": "https://nekoare.github.io/texture-color-adjuster/dev.nekoare.tex-col-adjuster-v${{ steps.version.outputs.version }}.zip",
            "zipSHA256": "$ZIP_HASH"
          }
          EOF
          
          # Update index.json with the new version
          jq --slurpfile newver new_version.json \
             '.packages["dev.nekoare.tex-col-adjuster"].versions["${{ steps.version.outputs.version }}"] = $newver[0]' \
             index.json > updated_index.json
          
          mv updated_index.json index.json
          rm new_version.json
          echo "Updated index.json with new version ${{ steps.version.outputs.version }}"
          
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
