name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Get package version
        id: version
        run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
        
      - name: Create package ZIP file
        run: |
          zip -r dev.nekoare.tex-col-adjuster-v${{ steps.version.outputs.version }}.zip . \
            -x "*.git*" "docs/*" "dev.nekoare.tex-col-adjuster-v*.zip" "*.Zone.Identifier" ".github/*"
          
      - name: Calculate ZIP hash and update index.json
        run: |
          ZIP_HASH=$(sha256sum dev.nekoare.tex-col-adjuster-v${{ steps.version.outputs.version }}.zip | cut -d' ' -f1)
          echo "Generated ZIP hash for v${{ steps.version.outputs.version }}: $ZIP_HASH"
          sed -i "s/PLACEHOLDER_HASH_TO_BE_UPDATED/$ZIP_HASH/g" docs/index.json
          echo "Updated docs/index.json with hash"
          
      - name: Move ZIP to docs directory
        run: mv dev.nekoare.tex-col-adjuster-v${{ steps.version.outputs.version }}.zip docs/
        
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
